### ISSUE TITLE
Erro: Could not find br.com.stone:stone-sdk:4.9.2 

### ISSUE THREAD

**Issue by mariolandossa** [Leleocastro/stone_payments#13]
Ao executar o build a lib não consegue localizar a SDK da Stone para baixar 

Launching lib/main.dart on L3 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find br.com.stone:stone-sdk:4.9.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/br/com/stone/stone-sdk/4.9.2/stone-sdk-4.9.2.pom
       - https://repo.maven.apache.org/maven2/br/com/stone/stone-sdk/4.9.2/stone-sdk-4.9.2.pom
       - https://storage.googleapis.com/download.flutter.io/br/com/stone/stone-sdk/4.9.2/stone-sdk-4.9.2.pom
       - https://packagecloud.io/priv/stone/pos-android/maven2/br/com/stone/stone-sdk/4.9.2/stone-sdk-4.9.2.pom
     Required by:
         project :app > project :stone_payments
   > Could not find br.com.stone:stone-sdk-posandroid:4.9.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/br/com/stone/stone-sdk-posandroid/4.9.2/stone-sdk-posandroid-4.9.2.pom
       - https://repo.maven.apache.org/maven2/br/com/stone/stone-sdk-posandroid/4.9.2/stone-sdk-posandroid-4.9.2.pom
       - https://storage.googleapis.com/download.flutter.io/br/com/stone/stone-sdk-posandroid/4.9.2/stone-sdk-posandroid-4.9.2.pom
       - https://packagecloud.io/priv/stone/pos-android/maven2/br/com/stone/stone-sdk-posandroid/4.9.2/stone-sdk-posandroid-4.9.2.pom
     Required by:
         project :app > project :stone_payments
   > Could not find br.com.stone:stone-sdk-posandroid-sunmi:4.9.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/br/com/stone/stone-sdk-posandroid-sunmi/4.9.2/stone-sdk-posandroid-sunmi-4.9.2.pom
       - https://repo.maven.apache.org/maven2/br/com/stone/stone-sdk-posandroid-sunmi/4.9.2/stone-sdk-posandroid-sunmi-4.9.2.pom
       - https://storage.googleapis.com/download.flutter.io/br/com/stone/stone-sdk-posandroid-sunmi/4.9.2/stone-sdk-posandroid-sunmi-4.9.2.pom
       - https://packagecloud.io/priv/stone/pos-android/maven2/br/com/stone/stone-sdk-posandroid-sunmi/4.9.2/stone-sdk-posandroid-sunmi-4.9.2.pom
     Required by:
         project :app > project :stone_payments
   > Could not find br.com.stone:stone-sdk-posandroid-ingenico:4.9.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/br/com/stone/stone-sdk-posandroid-ingenico/4.9.2/stone-sdk-posandroid-ingenico-4.9.2.pom
       - https://repo.maven.apache.org/maven2/br/com/stone/stone-sdk-posandroid-ingenico/4.9.2/stone-sdk-posandroid-ingenico-4.9.2.pom
       - https://storage.googleapis.com/download.flutter.io/br/com/stone/stone-sdk-posandroid-ingenico/4.9.2/stone-sdk-posandroid-ingenico-4.9.2.pom
       - https://packagecloud.io/priv/stone/pos-android/maven2/br/com/stone/stone-sdk-posandroid-ingenico/4.9.2/stone-sdk-posandroid-ingenico-4.9.2.pom
     Required by:
         project :app > project :stone_payments
   > Could not find br.com.stone:stone-sdk-posandroid-gertec:4.9.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/br/com/stone/stone-sdk-posandroid-gertec/4.9.2/stone-sdk-posandroid-gertec-4.9.2.pom
       - https://repo.maven.apache.org/maven2/br/com/stone/stone-sdk-posandroid-gertec/4.9.2/stone-sdk-posandroid-gertec-4.9.2.pom
       - https://storage.googleapis.com/download.flutter.io/br/com/stone/stone-sdk-posandroid-gertec/4.9.2/stone-sdk-posandroid-gertec-4.9.2.pom
       - https://packagecloud.io/priv/stone/pos-android/maven2/br/com/stone/stone-sdk-posandroid-gertec/4.9.2/stone-sdk-posandroid-gertec-4.9.2.pom
     Required by:
         project :app > project :stone_payments
   > Could not find br.com.stone:stone-sdk-posandroid-positivo:4.9.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/br/com/stone/stone-sdk-posandroid-positivo/4.9.2/stone-sdk-posandroid-positivo-4.9.2.pom
       - https://repo.maven.apache.org/maven2/br/com/stone/stone-sdk-posandroid-positivo/4.9.2/stone-sdk-posandroid-positivo-4.9.2.pom
       - https://storage.googleapis.com/download.flutter.io/br/com/stone/stone-sdk-posandroid-positivo/4.9.2/stone-sdk-posandroid-positivo-4.9.2.pom
       - https://packagecloud.io/priv/stone/pos-android/maven2/br/com/stone/stone-sdk-posandroid-positivo/4.9.2/stone-sdk-posandroid-positivo-4.9.2.pom
     Required by:
         project :app > project :stone_payments

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

**Comment by Leleocastro** [comment]
Você seguiu os passos que estão descritos na doc do package?
<img width="866" alt="image" src="https://github.com/user-attachments/assets/693aa943-c75a-49e1-9603-902a8e79e9a4">

Caso sim, forneça mais contexto do seu código, por favor. Como o build.gradle, por exemplo.

**Comment by mariolandossa** [comment]
faltou isso, obrigado
