### ISSUE TITLE
Onde consigo localizar o Acquirer Transaction Key 

### ISSUE THREAD

**Issue by mariolandossa** [Leleocastro/stone_payments#15]
Boa onde consigo pegar o Acquirer Transaction Key(ATK) no log informado pelo apk para preencher o formulário de homologação da Stone?

**Comment by CarvalhoWesley** [comment]
Boa Tarde @mariolandossa! No retorno do método transaction. Virá um objeto do tipo Transaction.

**Comment by mariolandossa** [comment]
Obrigado, no roteiro estão me pedindo "Realizar a ativação via StoneStart.init e apresentar o
UserModels populado com o StoneCode de teste." mas só consigo localizar no log  esse trecho, que não mostra o StoneCode:

D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
V/StoneStart( 4859): init()
D/Util    ( 4859): Serial Number: 4AB294Z1L
D/Connector( 4859): Connector: waitForService
D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 0
D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 0
D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
D/libc-netbsd( 4859): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
D/ServiceDeviceProvider( 4859): System Service connecting
D/Connector( 4859): Connector: connectService
D/Connector( 4859): Connector: waitForService
D/Connector( 4859): Service connected
D/Connector( 4859): Connector: waitForService
D/ServiceDeviceProvider( 4859): System Service connecting
D/Connector( 4859): Connector: connectService
D/Connector( 4859): Connector: waitForService
D/Connector( 4859): Service connected
D/MediaPlayer( 4859): Don't notify duration to br.com.infocast.infosigacmd!
D/MediaPlayer( 4859): setSubtitleAnchor in MediaPlayer
D/MediaPlayer( 4859): handleMessage msg:(1, 0, 0)
D/MediaPlayer( 4859): setSubtitleAnchor in MediaPlayer
D/Connector( 4859): Connector: waitForService
D/ServiceDeviceProvider( 4859): System Service connecting
D/Connector( 4859): Connector: connectService
D/Connector( 4859): Connector: waitForService
D/Connector( 4859): Service connected
D/PrinterManager( 4859): printerConnect: start
D/PrinterManager( 4859): printerConnect: end
D/PrinterManager( 4859): Service connected
D/Connector( 4859): Connector: waitForService
D/PrinterManager( 4859): Version Code: 1001006
D/PrinterManager( 4859): printerInit: start
D/PrinterManager( 4859): IPrinterCallback - onComplete
D/PrinterManager( 4859): printerInit: end
D/ServiceDeviceProvider( 4859): System Service connecting
D/Connector( 4859): Connector: connectService
D/Connector( 4859): Connector: waitForService
D/Connector( 4859): Service connected
I/art     ( 4859): Do partial code cache collection, code=37KB, data=62KB
I/art     ( 4859): After code cache collection, code=37KB, data=62KB
I/art     ( 4859): Increasing code cache capacity to 256KB

**Comment by CarvalhoWesley** [comment]
Boa tarde @mariolandossa, estou integrando um cliente atualmente e mandei um print do **StonePayments.activateStone** preenchido e expliquei o motivo no campo observações.

**Comment by mariolandossa** [comment]
@CarvalhoWesley qual motivo vc declarou ? Pois o suporte me aconselhou a colocar um breakpoint e capturar o log mas informei que era um plugin que faz a abstração do SDK e que ira ver com vc a possiblidade de colocar essa informação no Log.

**Comment by mariolandossa** [comment]
App validado para piloto, obrigado pela ajuda @CarvalhoWesley
