### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by bessajonathan** [Leleocastro/stone_payments#4]
Bom dia, curti bastante a ideia.
Sabe como funciona essa integração do sdk?
Exemplo: Na maquininha smart qnd chamo o método de pagamento abrirá o fluxo padrão da maquininha?

**Comment by Leleocastro** [comment]
Esse package é somente da Stone, não contempla a maquinha Smart da PagSeguro.

**Comment by bessajonathan** [comment]
Desculpe.Na verdade quis dizer sobre a maquinha smarth da própria stone

**Comment by Leleocastro** [comment]
Sim, abrirá o fluxo de pagamento, liberará para utilizar o cartão e caso necessite da senha, irá pedir também.

Lembrando que este package ele só inclui as maquininhas que são POS, não as que são via bluetooth.
