### ISSUE TITLE
Estou tendo esse erro

### ISSUE THREAD

**Issue by alexandreabade** [Leleocastro/stone_payments#5]
Attempt to invoke virtual method 'int br.com.setis.sunmi.bibliotecapinpad.AcessoDiretoPinpad.enviaComando(byte[], int)' on a null object reference

**Comment by Leleocastro** [comment]
@alexandreabade quando isso ocorre? Foi testado no app de exemplo adicionando o código de ativação?

**Comment by alexandreabade** [comment]
Foi sim no app de exemplo funciona , porem eu somente adicionando a biblioteca pelo e chamando os metodos no meu app mesmo estando configurado igual a library e main do kotlin no android ainda da o erro , obrigado pelo retorno amigo

**Comment by Leleocastro** [comment]
Olá @alexandreabade e desculpa a demora novamente. Poderia me dar mais contexto? Maquininha utilizada, log de erro...

**Comment by Leleocastro** [comment]
Fixed in new release #9
